# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='birthday',
            field=models.DateTimeField(default=None),
        ),
    ]
