# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0002_myuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateTimeField(default=None, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=64, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opman.RoleList', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.CharField(max_length=2, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='permissonlist',
            name='name',
            field=models.CharField(max_length=64, verbose_name='权限名称'),
        ),
        migrations.AlterField(
            model_name='permissonlist',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL地址'),
        ),
        migrations.AlterField(
            model_name='rolelist',
            name='name',
            field=models.CharField(max_length=64, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='rolelist',
            name='permission',
            field=models.ManyToManyField(blank=True, to='opman.PermissonList', verbose_name='权限'),
        ),
    ]
