# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0003_auto_20160608_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='生日'),
        ),
    ]
