# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0004_auto_20160612_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='生日'),
        ),
    ]
