# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0005_auto_20160612_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='permission',
            field=models.ManyToManyField(blank=True, to='opman.PermissonList', verbose_name='权限'),
        ),
    ]
