# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0006_myuser_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='opman.RoleList', verbose_name='部门'),
        ),
    ]
