# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0008_auto_20160612_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='nickname',
        ),
        migrations.AddField(
            model_name='myuser',
            name='fullname',
            field=models.CharField(max_length=64, null=True, verbose_name='姓名'),
        ),
    ]
