# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0009_auto_20160622_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaoQin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(blank=True, null=True, verbose_name='上班时间')),
                ('off', models.DateTimeField(blank=True, null=True, verbose_name='下班时间')),
                ('plus', models.TimeField(blank=True, null=True, verbose_name='加班时间')),
                ('late', models.TimeField(blank=True, null=True, verbose_name='迟到时间')),
                ('leave', models.TimeField(blank=True, null=True, verbose_name='请假时间')),
                ('content', models.CharField(max_length=100, null=True, verbose_name='情况分析')),
                ('fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
        ),
    ]
