# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0010_kaoqin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fullname',
            field=models.CharField(default=None, max_length=64, verbose_name='姓名'),
        ),
    ]
