# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0012_xlsx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlsx',
            name='filename',
            field=models.FileField(upload_to='./upload/xlsx/', verbose_name='选择文件'),
        ),
    ]
