# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0021_auto_20160705_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default=None, max_length=100, null=True, unique=True, verbose_name='GitLab域名')),
                ('rootoken', models.CharField(default=None, max_length=30, null=True, unique=True, verbose_name='管理员token')),
            ],
        ),
    ]
