# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0022_gitsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertoken', models.CharField(default=None, max_length=30, null=True, unique=True, verbose_name='用户token')),
                ('fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
        ),
    ]
