# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0026_auto_20160720_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='项目URL')),
                ('devpath', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='开发目录')),
                ('testpath', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='测试目录')),
                ('devhostname', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='开发域名')),
                ('testhostname', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='测试域名')),
            ],
        ),
        migrations.AddField(
            model_name='gitsetting',
            name='ngxpath',
            field=models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='nginx目录'),
        ),
        migrations.AlterField(
            model_name='gitsetting',
            name='sourcepath',
            field=models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='上线源目录'),
        ),
    ]
