# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opman', '0027_auto_20160721_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=30, verbose_name='上线名称')),
                ('projectname', models.CharField(default=None, max_length=30, verbose_name='项目名称')),
                ('applytime', models.DateTimeField(auto_now_add=True)),
                ('commitid', models.CharField(default=None, max_length=10, verbose_name='上线版本号')),
                ('status', models.IntegerField(default=None, verbose_name='是否上线')),
            ],
        ),
    ]
